<a href="https://colab.research.google.com/github/GerryMasaka/pca-svd/blob/main/pca_svd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.decomposition import TruncatedSVD,PCA

In [ ]:
svd=TruncatedSVD(3)
pca=PCA(3)

In [ ]:
size=100

In [ ]:
np.random.uniform(10,100,size)

array([18.78298319, 61.43849454, 41.35056325, 98.62860249, 49.45560507,
       45.28163079, 98.15563608, 26.36121572, 57.20205322, 91.43828398,
       85.85854254, 86.15558668, 20.98303651, 25.65139047, 62.00181678,
       76.84939538, 73.66543027, 58.1497494 , 35.1175105 , 48.24322494,
       29.12270891, 91.77028396, 86.0724622 , 48.02849045, 23.84248613,
       77.86966436, 19.22957897, 32.7768739 , 93.21389751, 24.36308464,
       65.39022484, 86.96708485, 50.39494465, 21.94825397, 53.79411176,
       52.54634091, 49.92686257, 61.1249738 , 30.02373508, 48.2521972 ,
       59.87285427, 89.29947277, 36.74619977, 52.15884717, 72.37749216,
       62.84647977, 39.12020317, 69.63171506, 11.95307608, 41.23108962,
       24.39836688, 67.86289275, 67.29256072, 94.10944883, 93.70150548,
       66.33587771, 96.43433476, 33.37499202, 38.65571807, 91.55677004,
       39.35755303, 34.95206719, 42.8052851 , 65.3750096 , 81.9758008 ,
       29.00354591, 78.02188561, 89.89156221, 46.50544758, 56.46

In [ ]:
data = pd.DataFrame ({'Loc':np.random.uniform(10,100,size) , 'Size':np.random.uniform(10,100,size) , 'Mail_Near':np.random.uniform(10,100,size), 'Ambience': np.random.uniform(10,100,size), 'Monthly_rent':np.random.uniform(10,100,size) })

In [ ]:
data

Loc       Size  Mail_Near   Ambience  Monthly_rent
0   71.566542  59.476267  54.680707  43.363274     12.945390
1   15.512034  22.394427  22.709548  70.642860     27.732787
2   11.161312  76.697899  64.503441  22.606601     57.839898
3   90.672699  44.475410  35.883263  33.176175     54.024911
4   12.933865  19.986689  38.211635  74.332150     66.045443
..        ...        ...        ...        ...           ...
95  37.947896  54.984121  82.462420  58.228117     19.032060
96  19.318371  77.048749  37.035500  12.695689     97.498751
97  52.913458  35.196170  57.102006  69.456475     68.113041
98  22.829835  35.616795  87.205192  75.440387     21.273349
99  77.424544  17.986299  63.159179  15.857003     88.642367

[100 rows x 5 columns]

In [ ]:
svd.fit_transform(data)

array([[106.6596421 ,   4.97763924,  43.355169  ],
       [ 71.15441302,  32.74912787,  -2.93993329],
       [104.74817605, -10.60301533, -29.88024268],
       [114.49902656,  -7.81019508,  22.17881523],
       [ 96.02613327,  16.58024854, -29.74327193],
       [117.90600563,  16.66576963, -25.55947293],
       [ 79.45766422,  -3.28446038,  -8.37869595],
       [ 99.09295434,  48.18047835,   4.31993368],
       [148.62861876, -36.00048212,  23.04006212],
       [138.76560396,  12.59013124, -31.76956369],
       [127.28256155,  37.14539844, -53.2481097 ],
       [114.95406413, -30.01448836, -19.25771693],
       [132.88970524,  25.70749143, -30.50879748],
       [124.89744757,  -1.6389049 ,  -1.58799847],
       [120.67634888,  52.88060525,  44.52157047],
       [137.8629423 ,  26.46637096,  45.01689919],
       [147.08107392,  50.25039943, -40.65108802],
       [112.47390662, -25.51271795,  -3.31469696],
       [139.26177266, -15.09453427,   3.6902318 ],
       [134.09130464,  58.21052

In [ ]:
pca.fit_transform(data)

array([[  6.31945546,  11.48620927,  46.47447968],
       [ 36.2686705 ,  37.26085888,   4.18390316],
       [ -8.53627003,  37.42649733, -23.02235195],
       [ -7.55978579,  -1.00096752,  22.37402298],
       [ 17.98210911,  16.94624416, -27.10419754],
       [ 16.75569283,   5.6317338 , -24.92552619],
       [  0.21216965,  44.76043338,   0.19339187],
       [ 49.29868058,   7.48215943,   5.82070761],
       [-38.02751992, -22.7247171 ,  19.09331856],
       [ 10.53650672, -21.7031622 , -36.64508353],
       [ 36.19237124,  -4.29212343, -55.08060954],
       [-29.66498871,   8.17630147, -18.08875829],
       [ 24.10944424, -17.35924367, -34.51233294],
       [ -1.9926135 ,  -1.8422233 ,  -1.94293061],
       [ 52.7602615 ,  -8.85037098,  43.73702363],
       [ 24.9933885 , -23.54845627,  41.3658393 ],
       [ 48.24404324, -13.6522501 , -43.91864669],
       [-23.56074308,  36.2428595 ,   3.89400427],
       [-16.19455027,  -7.81366801,   2.32991383],
       [ 57.15129876,  -7.92566